name: Toulouse JUG
description: Toulousains et passionnés des technos de la plateforme Java
markdown: kramdown
highlighter: pygments
safe: true
lsi: false
paginate: 5
encoding: UTF-8

baseurl: /
url: http://toulousejug.github.io
linkGoogleGroup: http://groups.google.com/group/toulouse-jug
linkTwitter: https://twitter.com/toulousejug
linkGithub: https://github.com/toulousejug
linkRSSFeeds: /feed
