baseurl = "https://www.toulousejug.org/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Toulouse JUG"
canonifyurls  = true

DefaultContentLanguage = "fr"
theme = "LessOrMore"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"

[Params]
  tagline = "Toulousains et passionnés des technos de la plateforme Java/JVM."
  logo = "images/logo.jpg"
  favicon = "images/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  lookingForSponsors = true
  next = "Soirée Java.Lang"
  nextDate = 2025-05-20
  nextFlyer = "images/2025-05-20-soiree-java-lang/promo.png"
  nextEvent = "https://www.meetup.com/toulouse-java-user-group/events/307529722"

[Author]
  name = "Toulouse JUG"
  googlegroup = "toulouse-jug"
  github = "toulousejug"
  twitter = "toulousejug"
  linkedin = "toulousejug"
  youtube = "channel/UCTqj9i8UpCNXRMcPNuWhocQ"
  meetup = "Toulouse-Java-User-Group"
